build_script:
- cmd: >-
    set QTDIR=C:\Qt\5.8\msvc2015

    set PATH=%PATH%;%QTDIR%\bin;

    cd suspend

    qmake suspend.pro

    %comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" x86

    C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
